---
layout: post
title: try,catch,final,throws
subtitle: 
gh-repo: 
gh-badge: [star, fork, follow]
tags: [Study, Spring]
categories : [Other]
---

자바는 실행중 Exception 발생 시 처리하는 걸 제공한다.   
이때 세가지 방법이 있는데.   
1) 메소드 내에서 직접처리하는 방법이있는데   
try, catch, final은 메소드내에서 예외처리 시에 사용된다.  
예로
~~~
try{

    예외 발생 가능성이 있는 문장들;

}catch(예외 타입1 매개변수명){

    예외타입1의 예외가 발생할 경우 처리 문장들;

}catch(예외 타입 n 매개변수명){

    예외타입 n의 예외가 발생할 경우 처리 문장들;

}finally{

    항상 수행할 필요가 있는 문장들;

}

~~~


2) 또 예외를 메소드를 호출한 다른 곳으로 예외처리를 보내버릴 수 있는데   
예외가 발생한 지점에서 try-catch 또는 try-catch-finally 블록을 이용하여 직접 처리하지 않아도 예외가 발생한 메소드를 호출한 지점으로 예외를 전달하여 처리하는 방법이 있다.   
이때 (throws) 가 사용된다.  

예로  
~~~
void 메소드() throws ClassNotFoundException{
~~~
호출받은 곳에선 try문ㅇ로 메소드를 호출하고 catch문으로 exception을 받아 처리해줘야한다.

3) 또 사용자가 exception class를 작성하여 발생 시킬 수있다.  
사용자가 예외 클래스를 정의하려면 예외 클래스의 최상위 클래스인 java.lang.Exception 클래스를 상속받아 클래스를 정의한다.

~~~
class 예외 클래스 이름 extends Exception
~~~

자바 가상 머신은 프로그램 수행중에 예외가 발생하면 자동으로 해당하는 예외 객체를 발생시킨 다음 catch 블록을 수행한다.
하지만 예외는 사용자가 강제적으로 발생시킬 수도 있다. 자바는 예외를 발생시키기 위해 throw 예약어를 사용한다.

~~~
throw new 예외 클래스 이름(매개변수);
~~~

throw를 이용한 예외 발생시에도 try-catch-finally 구문을 이용한 예외 처리를 하거나, throws를 이용하여 예외가 발생한 메소드를 호출한 다른 메소드로 넘기는 예외 처리 방법을 사용해야 한다.


